version: "3"

services:

  ckan:
    container_name: ckan
    build:
      context: ckan/
      dockerfile: Dockerfile
      args:
        - TZ=${TZ}
    env_file:
      - .env
    links:
      - solr
      - redis
      - datapusher-plus
    ports:
      - "0.0.0.0:${CKAN_PORT}:5000"
    volumes:
      - ckan_storage:/var/lib/ckan

  datapusher-plus:
    container_name: datapusher-plus
    platform: linux/amd64
    build:
      context: ./datapusher-plus
      dockerfile: Dockerfile
    ports:
      - "8800:8800"
    links:
      - ckan
    depends_on:
      - ckan
    env_file:
      - ./datapusher-plus/.env

  solr:
    container_name: solr
    image: ckan/ckan-solr:2.9-solr8
    volumes:
      - solr_data:/var/solr

  redis:
    container_name: redis
    image: redis:alpine

volumes:
  ckan_storage:
  pg_data:
  solr_data:
