version: "3"

services:

  ckan-dev:
    container_name: ckan-dev
    platform: linux/x86_64
    build:
      context: ckan/
      dockerfile: Dockerfile.dev
      args:
        - TZ=${TZ}
    env_file:
      - .env
    links:
      - db
      - solr
      - redis
      - datapusher-plus
    ports:
      - "0.0.0.0:${CKAN_PORT}:5000"
    volumes:
      - ./src:/srv/app/src_extensions
      - ckan_storage:/var/lib/ckan

  datapusher-plus:
      container_name: datapusher-plus
      build:
        context: ./datapusher-plus
        dockerfile: Dockerfile
      ports:
        - "8800:8800"
      links:
        - db
        - redis
      env_file:
        - datapusher-plus/.env
      environment:
        - SQLALCHEMY_DATABASE_URI=postgresql://datapusher_jobs:${DATAPUSHER_PASSWORD}@db/datapusher_jobs
        - WRITE_ENGINE_URL=postgresql://datapusher:${DATAPUSHER_JOBS_PASSWORD}@db/datastore_default

  db:
    container_name: db
    env_file:
      - .env
    build:
      context: postgresql/
    ports:
      - "5432:5432"
    environment:
      - PGDATA=/var/lib/postgresql/data/db
    volumes:
      - pg_data:/var/lib/postgresql/data

  solr:
    container_name: solr
    image: ckan/ckan-solr:2.9-solr8
    ports:
      - "8983:8983"
    volumes:
      - solr_data:/var/solr

  redis:
    container_name: redis
    image: redis:alpine

volumes:
  ckan_storage:
  pg_data:
  solr_data:
