version: "3"

services:

  ckan-dev:
    container_name: ckan-dev
    platform: linux/x86_64
    build:
      context: ckan/
      dockerfile: Dockerfile.dev
      args:
        - TZ=${TZ}
    env_file:
      - .env
    links:
      - db
      - solr
      - redis
    ports:
      - "0.0.0.0:${CKAN_PORT}:5000"
    volumes:
      - ./src:/srv/app/src_extensions
      - ckan_storage:/var/lib/ckan

  datapusher-plus:
    container_name: datapusher-plus
    platform: linux/arm64/v8
    build:
      context: ./datapusher-plus
      dockerfile: Dockerfile
    ports:
      - "8800:8800"
    links:
      - ckan-dev
      - db
    depends_on:
      - db
      - ckan-dev
    env_file:
      - ./datapusher-plus/.env

  db:
    container_name: db
    env_file:
      - .env
    build:
      context: postgresql/
    ports:
      - "5433:5432"
    shm_size: 12g
    environment:
      - PGDATA=/var/lib/postgresql/data/db
    volumes:
      - pg_data:/var/lib/postgresql/data

  solr:
    container_name: solr
    image: ckan/ckan-solr:2.10-solr9
    ports:
      - "8983:8983"
    volumes:
      - solr_data:/var/solr

  redis:
    container_name: redis
    image: redis:alpine

  # martin - tile server
  tiles:
    image: ghcr.io/maplibre/martin:v0.8.7
    platform: linux/x86_64
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - "DATABASE_URL=${CKAN_DATASTORE_READ_URL}"
      - RUST_LOG=actix_web=info,martin=debug,tokio_postgres=debug

volumes:
  ckan_storage:
  pg_data:
  solr_data:
